global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "user_service"
    static_configs:
      - targets: ["user-service:3001"]

  - job_name: "campaign_service"
    static_configs:
      - targets: ["campaign-service:3002"]

  - job_name: "pledge_service"
    static_configs:
      - targets: ["pledge-service:3003"]

  - job_name: "payment_service"
    static_configs:
      - targets: ["payment-service:3004"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
